title: VR Performance Toolkit
description: >- # this means to ignore newlines until "baseurl:"
  A collection of tools to help you make your PCVR games run faster without
  sacrificing too much visual quality.

# Build settings
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
